sudo: no
dist: trusty
addons:
  mariadb: "10.0"
env:
  - DATABASES_MYSQL_NAME=django_project
  - DATABASES_MYSQL_USER=www
  - DATABASES_MYSQL_PASSWORD=123456
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"
before_install:
  - mysql -e "CREATE USER '${DATABASES_MYSQL_USER}'@'%' IDENTIFIED BY '${DATABASES_MYSQL_PASSWORD}';"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO '${DATABASES_MYSQL_NAME}'@'%' IDENTIFIED BY '${DATABASES_MYSQL_PASSWORD}' WITH GRANT OPTION;"
  - mysql -e "FLUSH PRIVILEGES;"
  - mysql -e "CREATE DATABASE IF NOT EXISTS ${DATABASES_MYSQL_NAME};"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
before_script:
  - mysql -e "SOURCE db/schema/mysql.sql; SOURCE db/data/mysql.sql; SHOW databases; SHOW tables;"
script:
  - cd app_frontend
  # Copy the coveragerc down so coverage.py can find it.
  - cp ../.coveragerc .
  # Travis workers are often overloaded and cause our tests to exceed
  - python manage.py test
  - coverage run --source='.' manage.py test
after_script:
  - mysql -e "DROP DATABASE IF EXISTS ${DATABASES_MYSQL_NAME}" ;
after_success: coveralls
